### ISSUE TITLE
安装YCM后，报错 Error retrieving completer debug info

### ISSUE THREAD

**Issue by WM-CH** [yangyangwithgnu/use_vim_as_ide#96]
我是VIM8.1源码安装的
并且使用的是编译好的二进制llvm+clang8.0.0
安装完仍然出错如下：

2019-03-30 20:15:41,394 - ERROR - Error retrieving completer debug info
Traceback (most recent call last):
  File "/home/book/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 234, in DebugInfo
    request_data ).DebugInfo( request_data )
  File "/home/book/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 298, in _GetCompleterForRequestData
    return _server_state.GetFiletypeCompleter( request_data[ 'filetypes' ] )
  File "/home/book/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/server_state.py", line 80, in GetFiletypeCompleter
    for filetype in current_filetypes ]
  File "/home/book/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/server_state.py", line 63, in _GetFiletypeCompleterForFiletype
    module = import_module( 'ycmd.completers.{}.hook'.format( filetype ) )
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ValueError: Empty module name

最近折腾了N次都是这个错误，不知道什么原因，请各位帮忙分析下，谢谢了

**Comment by WM-CH** [comment]
:YcmToggleLogs
Which logfile do you wish to open (or close if already open)?
1: ycm_ftm6fgm2.log
2: ycmd_36837_stderr_rqz0x65g.log
3: ycmd_36837_stdout_gq6u4i1f.log

选2查看的

**Comment by WM-CH** [comment]
上边的问题解决了，是因为在ycm_extra_config.py里面默认支持的是c++，当我打开c文件的时候，就会报这个错误。
在.py里改成对c语言补全就没有错误了。
